### ISSUE TITLE
Error: `sudo: command not found` when deploying VMs 

### ISSUE THREAD

**Issue by kunleoladimeji** [bpg/terraform-provider-proxmox#962]
**Describe the bug**
I get the error (bash: line 1: sudo: command not found) when trying to create VMs.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a resource
2. Run 'terraform apply'
3. See error

Please also provide a minimal Terraform configuration that reproduces the issue.

```hcl
provider "proxmox" {
}
variable "proxmox_target_node" {
  type        = string
  description = "Proxmox target node"
  default     = "pve-1"
}
data "tls_public_key" "ssh_key" {
  private_key_openssh = file(pathexpand("~/.ssh/id_rsa"))
}
resource "proxmox_virtual_environment_file" "cloudinit_userdata" {
  content_type = "snippets"
  datastore_id = "local"
  node_name = var.proxmox_target_node
  source_file {
    path = "./files/user_data_ubuntu.yaml"
    checksum = sha256(file("./files/user_data_ubuntu.yaml"))
    file_name = "ubuntu.cloud-config.yaml"
  }
}
resource "proxmox_virtual_environment_file" "ubuntu_lunar_cloud_kvm_image" {
  content_type = "iso"
  datastore_id = "local"
  overwrite = false
  node_name    = var.proxmox_target_node

  source_file {
    path = "https://cloud-images.ubuntu.com/lunar/current/lunar-server-cloudimg-amd64-disk-kvm.img"
  }
}
resource "proxmox_virtual_environment_vm" "redis" {
  description = "Redis Server"
  node_name   = var.proxmox_target_node
  name        = "redis"
  tags        = ["redis"]
  agent {
    enabled = true
    trim    = true
  }
  disk {
    datastore_id = "local-lvm"
    file_id      = proxmox_virtual_environment_file.ubuntu_lunar_cloud_kvm_image.id
    interface    = "virtio0"
    size         = 15
    discard      = "on"
  }
  memory {
    dedicated = 512
  }
  operating_system {
    type = "l26"
  }
  initialization {
    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }
    user_account {
      keys     = [trimspace(data.tls_public_key.ssh_key.public_key_openssh)]
      password = var.override_password
      username = "ubuntu"
    }
    user_data_file_id = proxmox_virtual_environment_file.cloudinit_userdata.id
  }
  lifecycle {
    ignore_changes = [description]
  }
  serial_device {}
  vga {
    enabled = true
    memory  = 16
    type    = "serial0"

  }
  network_device {
    bridge = "vmbr0"
  }
}

```

**Expected behavior**
Create the VMs with no errors

**Screenshots**

**Additional context**
Environment variables `PROXMOX_VE_USERNAME`, `PROXMOX_VE_PASS` and `PROXMOX_VE_ENDPOINT` are already set.

The workflow works fine on version 0.44.0 of this provider.

- Single or clustered Proxmox: Single Proxmox
- Provider version (ideally it should be the latest version): Latest 0.45.0
- Terraform version: Terraform v1.7.1
- OS (where you run Terraform from): MacOS
- Debug logs (`TF_LOG=DEBUG terraform apply`):
```
2024-01-26T11:43:42.373+0400 [DEBUG] provider.terraform-provider-proxmox_v0.45.0: SSH connection established: @module=proxmox user=root host=192.168.1.10:22 tf_mux_provider=tf5to6server.v5tov6Server tf_provider_addr=registry.terraform.io/bpg/proxmox tf_req_id=6ed73c1b-89d0-35fe-b46f-ce7d119819de @caller=github.com/bpg/terraform-provider-proxmox/proxmox/ssh/client.go:297 tf_resource_type=proxmox_virtual_environment_vm tf_rpc=ApplyResourceChange timestamp="2024-01-26T11:43:42.373+0400"
2024-01-26T11:43:42.646+0400 [ERROR] provider.terraform-provider-proxmox_v0.45.0: Failed to close: @caller=github.com/bpg/terraform-provider-proxmox/utils/io.go:20 error=EOF tf_provider_addr=registry.terraform.io/bpg/proxmox tf_req_id=6ed73c1b-89d0-35fe-b46f-ce7d119819de tf_resource_type=proxmox_virtual_environment_vm tf_rpc=ApplyResourceChange @module=proxmox tf_mux_provider=tf5to6server.v5tov6Server timestamp="2024-01-26T11:43:42.646+0400"
2024-01-26T11:43:42.646+0400 [ERROR] provider.terraform-provider-proxmox_v0.45.0: Response contains error diagnostic: @module=sdk.proto diagnostic_severity=ERROR tf_proto_version=6.4 tf_resource_type=proxmox_virtual_environment_vm tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/internal/diag/diagnostics.go:62
  diagnostic_summary=
  | bash: line 1: sudo: command not found
   diagnostic_detail="" tf_provider_addr=registry.terraform.io/bpg/proxmox tf_req_id=6ed73c1b-89d0-35fe-b46f-ce7d119819de timestamp="2024-01-26T11:43:42.646+0400"
2024-01-26T11:43:42.647+0400 [ERROR] provider.terraform-provider-proxmox_v0.45.0: Failed to close: @caller=github.com/bpg/terraform-provider-proxmox/utils/io.go:20 error=EOF tf_mux_provider=tf5to6server.v5tov6Server tf_req_id=eb67bbc5-2f8e-d76d-8940-6c61ecd0b34b @module=proxmox tf_provider_addr=registry.terraform.io/bpg/proxmox tf_resource_type=proxmox_virtual_environment_vm tf_rpc=ApplyResourceChange timestamp="2024-01-26T11:43:42.647+0400"
2024-01-26T11:43:42.648+0400 [ERROR] provider.terraform-provider-proxmox_v0.45.0: Response contains error diagnostic: diagnostic_detail=""
  diagnostic_summary=
  | bash: line 1: sudo: command not found
   diagnostic_severity=ERROR tf_proto_version=6.4 tf_provider_addr=registry.terraform.io/bpg/proxmox @module=sdk.proto tf_resource_type=proxmox_virtual_environment_vm tf_rpc=ApplyResourceChange tf_req_id=eb67bbc5-2f8e-d76d-8940-6c61ecd0b34b @caller=github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/internal/diag/diagnostics.go:62 timestamp="2024-01-26T11:43:42.648+0400"
2024-01-26T11:43:42.660+0400 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot
2024-01-26T11:43:42.660+0400 [ERROR] vertex "proxmox_virtual_environment_vm.redis" error: bash: line 1: sudo: command not found
2024-01-26T11:43:42.669+0400 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot
2024-01-26T11:43:42.669+0400 [ERROR] vertex "proxmox_virtual_environment_vm.gitlab" error: bash: line 1: sudo: command not found
╷
│ Error: bash: line 1: sudo: command not found
│ 
│ 
│   with proxmox_virtual_environment_vm.redis,
│   on databases.tf line 104, in resource "proxmox_virtual_environment_vm" "redis":
│  104: resource "proxmox_virtual_environment_vm" "redis" {
│ 
╵
╷
│ Error: bash: line 1: sudo: command not found
│ 
│ 
│   with proxmox_virtual_environment_vm.gitlab,
│   on gitlab.tf line 1, in resource "proxmox_virtual_environment_vm" "gitlab":
│    1: resource "proxmox_virtual_environment_vm" "gitlab" {
│ 
╵
2024-01-26T11:43:42.685+0400 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2024-01-26T11:43:42.687+0400 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/bpg/proxmox/0.45.0/darwin_arm64/terraform-provider-proxmox_v0.45.0 pid=21259
2024-01-26T11:43:42.687+0400 [DEBUG] provider: plugin exited
```

**Comment by bpg** [comment]
Hi @kunleoladimeji! 👋🏼 Thanks for the report.

This is a regression after #352 was implemented in v0.45.

I see your provider is using `root` user for SSH, so I don't see why `sudo` is not available for this user. I was implementing this under the assumption that `sudo` is installed by default, but that might not be the case for your PVE instance. What is the Proxmox version you are using?

**Comment by bpg** [comment]
Okay, it looks like `sudo` is not installed by default in PVE 🤦🏼
I'll add some detection & error handling logic around those calls, so it will fall back to the old approach if sudo is not available.

**Comment by kunleoladimeji** [comment]
Thanks for looking into this.

I tested the new release 0.45.1 and I'm happy to say that the issue is resolved.
